"""rename department

Revision ID: 8ccbb41ef9b8
Revises: c17b998e2452
Create Date: 2025-01-18 23:59:37.318838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccbb41ef9b8'
down_revision = 'c17b998e2452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')
    # ### end Alembic commands ###
